version: '3'

services:
  project-clean-ddd:
    build:
      context: .
      dockerfile: Dockerfile
    image: project-clean-ddd
    container_name: project-clean-ddd
    ports:
      - 3333:3333
    networks:
      - app-network
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - HOST=${HOST}
    restart: always

networks:
  app-network:
    name: 'app-network'
    driver: bridge
